// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Form");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "container"
                        }, React.createElement("form", {
                              className: "form-horizontal"
                            }, React.createElement("div", {
                                  className: "form-group has-feedback"
                                }, React.createElement("br", undefined), React.createElement("div", {
                                      className: "col-sm-10"
                                    }, React.createElement("div", undefined, "moi")))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var databases = /* :: */[
  "Melinda",
  /* :: */[
    "Aalto-yliopisto",
    /* :: */[
      "Arcada",
      /* :: */[
        "Centria",
        /* :: */[
          "DIAK",
          /* :: */[
            "Fennica",
            /* :: */[
              "Haaga-Helia",
              /* :: */[
                "HAMK",
                /* :: */[
                  "Hanken",
                  /* :: */[
                    "Helka",
                    /* :: */[
                      "Humak",
                      /* :: */[
                        "It\xc3\xa4-Suomen yliopisto",
                        /* :: */[
                          "Jyv\xc3\xa4skyl\xc3\xa4n ammattikorkeakoulu",
                          /* :: */[
                            "Jyv\xc3\xa4skyl\xc3\xa4n yliopisto",
                            /* :: */[
                              "Kaakkois-Suomen amk",
                              /* :: */[
                                "Kajaanin ammattikorkeakoulu",
                                /* :: */[
                                  "Karelia-ammattikorkeakoulu",
                                  /* :: */[
                                    "Lapin korkeakoulukirjasto",
                                    /* :: */[
                                      "Lappeenrannan tiedekirjasto",
                                      /* :: */[
                                        "LAMK",
                                        /* :: */[
                                          "Laurea-ammattikorkeakoulu",
                                          /* :: */[
                                            "Metropolia",
                                            /* :: */[
                                              "OAMK",
                                              /* :: */[
                                                "Oulun yliopisto",
                                                /* :: */[
                                                  "SAMK",
                                                  /* :: */[
                                                    "Savonia",
                                                    /* :: */[
                                                      "SeAMK",
                                                      /* :: */[
                                                        "Taideyliopisto",
                                                        /* :: */[
                                                          "TAMK",
                                                          /* :: */[
                                                            "Tampereen yliopisto",
                                                            /* :: */[
                                                              "Tritonia",
                                                              /* :: */[
                                                                "Turku AMK",
                                                                /* :: */[
                                                                  "Turun kaupunginkirjasto",
                                                                  /* :: */[
                                                                    "Turun yliopisto",
                                                                    /* :: */[
                                                                      "Varastokirjasto",
                                                                      /* :: */[
                                                                        "\xc3\x85bo Akademi",
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var instructions = /* :: */[
  "MARC 21",
  /* :: */[
    "MARC 21 Full (LOC)",
    /* :: */[
      "MARC 21 sovellusohje (RDA)",
      /* [] */0
    ]
  ]
];

exports.databases = databases;
exports.instructions = instructions;
exports.component = component;
exports.make = make;
/* component Not a pure module */
